// <auto-generated />
namespace QuanLyKhoaLuan.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addTableThese : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addTableThese));
        
        string IMigrationMetadata.Id
        {
            get { return "202212280855421_addTableThese"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
