// <auto-generated />
namespace QuanLyKhoaLuan.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class validate_department : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(validate_department));
        
        string IMigrationMetadata.Id
        {
            get { return "202212161346485_validate_department"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
