// <auto-generated />
namespace QuanLyKhoaLuan.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class datime_foundingdat : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(datime_foundingdat));
        
        string IMigrationMetadata.Id
        {
            get { return "202212170732199_datime_foundingdat"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
