// <auto-generated />
namespace QuanLyKhoaLuan.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addtablethese_reg : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addtablethese_reg));
        
        string IMigrationMetadata.Id
        {
            get { return "202212300249501_addtablethese_reg"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
